http://localhost:5000/Users

###
http://localhost:5000/Users
###

POST http://localhost:5000/users 
Content-Type: application/json

{
    "name": "John Doe", "judul": "surat", "note": "lorem ipsum"
    }